### PR TITLE
profile page change

### PR DESCRIPTION
**Pull request by yemoski**
Profile page changes -> removing the search bar and making the name and info about the user central

### CODE REVIEW

**Comment by yemoski** [comment]
image

**Comment by yemoski** [comment]
I removed the account type on the register page as a user automatically becomes an admin when they create an account
image

**Comment by yemoski** [comment]
image

**Comment by yemoski** [comment]
image

**Comment by yemoski** [comment]
reverting the register page change

**Review by Abdulhameed23 — APPROVED** [review]

**Pull request merged**
